[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.build]
cmds = [
  "mix deps.get --only prod",
  "MIX_ENV=prod mix compile",
  "npm --prefix assets install --legacy-peer-deps",
  "npm run --prefix assets build",
  "MIX_ENV=prod mix assets.deploy",
  "MIX_ENV=prod mix release"
]

[start]
cmd = "bin/mention_score start"
